### ISSUE TITLE
Bug in StringUtils.startsWithIgnoringCaseAndWhitespaces() prevents writing out "J"

### ISSUE THREAD

**Issue by erik-alm** [casid/jte#305]
`StringUtils.startsWithIgnoringCaseAndWhitespaces()` is implemented "backwards". Instead of trying to find the prefix in the string, it tries to find the string in the prefix. This causes this undesired behavior:

    final String string = "J";
    final String prefix = "javascript";
    System.out.println(startsWithIgnoringCaseAndWhitespaces(string, prefix)); // result: true

It also means you cannot write a variable with the content "J" or "Ja" etc. when it's part of an "a href"-attribute like:

    <a data-toggle="tab" href="#key_${key}">${key}</a>

Trying to fix the problem using "unsafe", like so:

    <a data-toggle="tab" href="#key_$unsafe{key}">${key}</a>

…seems to cause another bug (since "key" is a "Character"? — I had to convert it to a `String` to make it work):

    gg.jte.TemplateException: Failed to compile template, error at pages/browse.jte:82
    .../jte-classes/gg/jte/generated/ondemand/pages/JtebrowseGenerated.java:64: error: incompatible types: Character cannot be converted to String
					jteOutput.writeUnsafeContent(key);
					                             ^
    .../jte-classes/gg/jte/generated/ondemand/pages/JtebrowseGenerated.java:71: error: incompatible types: Character cannot be converted to String
					jteOutput.writeUnsafeContent(key);
					                             ^
    Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
    2 errors

	at gg.jte.compiler.java.JavaClassCompiler.runCompiler(JavaClassCompiler.java:49)
	at gg.jte.compiler.java.JavaClassCompiler.compile(JavaClassCompiler.java:38)
	at gg.jte.compiler.TemplateCompiler.precompileClasses(TemplateCompiler.java:114)
	at gg.jte.compiler.TemplateCompiler.precompile(TemplateCompiler.java:94)
	at gg.jte.compiler.TemplateCompiler.load(TemplateCompiler.java:50)
	at gg.jte.TemplateEngine.lambda$resolveTemplateOnDemand$0(TemplateEngine.java:354)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1955)
	at gg.jte.TemplateEngine.resolveTemplateOnDemand(TemplateEngine.java:347)
	at gg.jte.TemplateEngine.resolveTemplate(TemplateEngine.java:337)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:210)
	at net.blockm.starmap.web.WebRepository.render(WebRepository.java:36)
	at net.blockm.starmap.app.WebBuilder.writeIndex(WebBuilder.java:1269)
	at net.blockm.starmap.app.WebBuilder.buildGroupsIndex(WebBuilder.java:585)
	at net.blockm.starmap.app.WebBuilder.build(WebBuilder.java:87)
	at net.blockm.starmap.app.Main.main(Main.java:145)

**Comment by casid** [comment]
I just released jte version 3.1.6, containing a fix for this issue.

**Comment by erik-alm** [comment]
Great! It seems to work. Though "unsafe(Character)" is still broken.

**Comment by casid** [comment]
$unsafe has only implementations for String and Content, since usually it does not make sense to have unsafe for single characters.
