### ISSUE TITLE
Kotlin 2.1 warning due to JTE accessing hidden compiler symbols.

### ISSUE THREAD

**Issue by sureshg** [casid/jte#407]
Kotlin 2.1 now throws a warning and will soon prohibit accessing `kotlin-compiler-embeddable` from build scripts. I am now starting to get warning messages from build scripts which use the`JTE` plugin. When i checked the dependencies for the build plugin, `kotlin-compiler-embeddable` is used by JTE and the Kotlin 2.1 doc suggests the following [workaround](https://kotlinlang.org/docs/whatsnew21.html#compiler-symbols-hidden-from-the-kotlin-gradle-plugin-api) to fix the issue.

```
org.jetbrains.kotlin:kotlin-compiler-embeddable:1.9.10 -> 2.1.0
\--- gg.jte:jte-kotlin:3.1.15
     \--- gg.jte:jte-gradle-plugin:3.1.15
          \--- runtimeClasspath
```

```
> Configure project :shared
w: The artifact `org.jetbrains.kotlin:kotlin-compiler-embeddable` is present in the build classpath along Kotlin Gradle plugin.
This may lead to unpredictable and inconsistent behavior.
For more details, see: https://kotl.in/gradle/internal-compiler-symbols

> Configure project :web
w: The artifact `org.jetbrains.kotlin:kotlin-compiler-embeddable` is present in the build classpath along Kotlin Gradle plugin.
This may lead to unpredictable and inconsistent behavior.
For more details, see: https://kotl.in/gradle/internal-compiler-symbols
```

**Comment by casid** [comment]
Is this fixed in jte 3.2.0?

**Comment by sureshg** [comment]
@casid thanks for 3.2.0 release, but i can still see these warnings. 

Instead of direclty pulling [this](https://github.com/casid/jte/blob/main/jte-kotlin/pom.xml#L22-L26), should we we need to use something like https://kotlinlang.org/docs/whatsnew21.html#using-the-gradle-workers-api

```
org.jetbrains.kotlin:kotlin-compiler-embeddable:2.1.20
\--- org.jetbrains.kotlin:kotlin-bom:2.1.20
     +--- runtimeClasspath
     \--- com.github.ben-manes:gradle-versions-plugin:0.52.0 (requested org.jetbrains.kotlin:kotlin-bom:2.0.21)
          \--- com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.52.0
               \--- runtimeClasspath

org.jetbrains.kotlin:kotlin-compiler-embeddable:2.1.10 -> 2.1.20
\--- gg.jte:jte-kotlin:3.2.0
     \--- gg.jte:jte-gradle-plugin:3.2.0
          \--- gg.jte.gradle:gg.jte.gradle.gradle.plugin:3.2.0
               \--- runtimeClasspath

```

**Comment by schowave** [comment]
I am working on this here, but could use some support: https://github.com/casid/jte/pull/445
